/* Auto-generated by genmsg_cpp for file /home/user/ros_workspace/sandbox/SkypeRobot/msg/Whells.msg */
#ifndef SKYPEROBOT_MESSAGE_WHELLS_H
#define SKYPEROBOT_MESSAGE_WHELLS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace SkypeRobot
{
template <class ContainerAllocator>
struct Whells_ {
  typedef Whells_<ContainerAllocator> Type;

  Whells_()
  : LeftWhell(0)
  , RightWhell(0)
  {
  }

  Whells_(const ContainerAllocator& _alloc)
  : LeftWhell(0)
  , RightWhell(0)
  {
  }

  typedef int16_t _LeftWhell_type;
  int16_t LeftWhell;

  typedef int16_t _RightWhell_type;
  int16_t RightWhell;


  typedef boost::shared_ptr< ::SkypeRobot::Whells_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::SkypeRobot::Whells_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Whells
typedef  ::SkypeRobot::Whells_<std::allocator<void> > Whells;

typedef boost::shared_ptr< ::SkypeRobot::Whells> WhellsPtr;
typedef boost::shared_ptr< ::SkypeRobot::Whells const> WhellsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::SkypeRobot::Whells_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::SkypeRobot::Whells_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace SkypeRobot

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::SkypeRobot::Whells_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::SkypeRobot::Whells_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::SkypeRobot::Whells_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e5ada9f49e71063ab0b92ab955b7d877";
  }

  static const char* value(const  ::SkypeRobot::Whells_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe5ada9f49e71063aULL;
  static const uint64_t static_value2 = 0xb0b92ab955b7d877ULL;
};

template<class ContainerAllocator>
struct DataType< ::SkypeRobot::Whells_<ContainerAllocator> > {
  static const char* value() 
  {
    return "SkypeRobot/Whells";
  }

  static const char* value(const  ::SkypeRobot::Whells_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::SkypeRobot::Whells_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int16    LeftWhell\n\
int16    RightWhell\n\
\n\
";
  }

  static const char* value(const  ::SkypeRobot::Whells_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::SkypeRobot::Whells_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::SkypeRobot::Whells_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.LeftWhell);
    stream.next(m.RightWhell);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Whells_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::SkypeRobot::Whells_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::SkypeRobot::Whells_<ContainerAllocator> & v) 
  {
    s << indent << "LeftWhell: ";
    Printer<int16_t>::stream(s, indent + "  ", v.LeftWhell);
    s << indent << "RightWhell: ";
    Printer<int16_t>::stream(s, indent + "  ", v.RightWhell);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SKYPEROBOT_MESSAGE_WHELLS_H

